QLTD/QLTD/ViewModels/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ehr.ViewModels
{
    public class ReportViewModel
    {
        /// <summary>
        /// Mã khách hàng
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Tên khách hàng
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Số điện thoại
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// Địa chỉ
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// Tổng đĩa đang thuê
        /// </summary>
        public int DiskRentTotal { get; set; }
        /// <summary>
        /// Tổng đĩa trễ hạn
        /// </summary>
        public int DiskLate { get; set; }
        /// <summary>
        /// Tên đĩa
        /// </summary>
        public string Disk { get; set; }
    }
}

QLTD/QLTD/Controllers/ReportController.cs
using Ehr.Auth;
using Ehr.Bussiness;
using Ehr.Common.Constraint;
using Ehr.Common.UI;
using Ehr.Data;
using Ehr.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ehr.Controllers
{
    public class ReportController : BaseController
    {
        private readonly UnitWork unitWork;
        public ReportController(UnitWork unitWork)
        {
            this.unitWork = unitWork;
        }
        [PermissionBasedAuthorize("DISK_MNT")]
        public ActionResult All(string sortProperty, string sortOrder, string searchString, int? size, int? page)
        {
            var user = unitWork.User.GetById(this.User.UserId);
            if (String.IsNullOrEmpty(sortProperty)) sortProperty = "Code";
            //Mặc định là từ A-Z
            string nextSort = "";
            if (String.IsNullOrEmpty(sortOrder)) sortOrder = "desc";
            if (sortOrder.Equals("asc") | sortOrder.Equals("none")) nextSort = "desc";
            if (sortOrder.Equals("desc")) nextSort = "asc";


            //Tạo danh sách cho hiển thị số dòng trên lưới
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "35", Value = "35" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });
            items.Add(new SelectListItem { Text = "100", Value = "100" });
            items.Add(new SelectListItem { Text = "200", Value = "200" });
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }

            QLTDDBContext db = new QLTDDBContext();
            //Lấy dataset rỗng
            var lsReport = new List<ReportViewModel>();

            var lscus = unitWork.Customer.Get();
            foreach (var item in lscus)
            {
                var rp = new ReportViewModel();
                rp.Code = item.Code;
                rp.Name = item.Name;
                rp.PhoneNumber = item.PhoneNumber;
                rp.Address = item.Address;
                var getall = unitWork.RentDetail.Get(X => X.Disk.Status == DiskStatus.RENTING && X.Rent.Customer.Id == item.Id);
                var numlate = unitWork.RentDetail.Get(X => X.Disk.Status == DiskStatus.RENTING && X.Rent.Customer.Id == item.Id && X.Rent.ReceiptDate.Date < DateTime.Now).Count();
                var disk = getall.Select(x => x.Disk.DiskTitle.Name).Distinct().OrderBy(c => c).ToList();
                foreach (var item1 in disk)
                {
                    rp.Disk += " - " + item1;
                }
                lsReport.Add(rp);
            }

            #region Phần phân trang		
            //Trang mặc định
            if (page == null) page = 1;
            //Số dòng mặc định
            int pageSize = (size ?? 10);
            // Đếm tổng số trang

            int datasetSize = 0;
            if (lsReport != null)
                datasetSize = lsReport.Count();
            int checkTotal = (int)(datasetSize / pageSize) + 1;
            // Nếu trang yêu cầu vượt qua tổng số trang thì thiết lập là tổng số trang
            if (page > checkTotal) page = checkTotal;
            string _url = "searchString=" + searchString + "&sortProperty=" + sortProperty + "&sortOrder=" + sortOrder;
            EZPaging ezpage = new EZPaging((page ?? 1), pageSize, datasetSize, _url);
            #endregion

            ViewBag.searchValue = searchString;// Chuỗi tìm kiếm
            ViewBag.sortProperty = sortProperty;//Chọn cột sắp xếp
            ViewBag.sortOrder = nextSort;//Kiểu sắp xếp tiếp theo
            ViewBag.page = page;// Trang hiện tại
            ViewBag.size = items; //Danh sách cho chọn trang
            ViewBag.currentSize = size; //Số mục trên 1 trang được chọn
            ViewBag.pageSize = pageSize;//Số mục trên 1 trang để cache lại
            ViewBag.paging = ezpage.PageModel.HTML;//HTML cho đoạn phân trang
            ViewBag.fromItem = ezpage.PageModel.StartItem;

            //Hiển thị trong khoảng chọn
            if (ezpage.PageModel.StartItem >= 1 && datasetSize > 0)
            {
                return View(lsReport.Skip(ezpage.PageModel.StartItem - 1).Take(ezpage.PageModel.StopItem - ezpage.PageModel.StartItem + 1).ToList());
            }
            else
            {
                return View(lsReport);
            }
        }

    }
}

QLTD/QLTD/Views/Report/All.cshtml
@{
    ViewBag.Title = "Thống kê tất cả khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Ehr.Data.QLTDDBContext db = new Ehr.Data.QLTDDBContext();
    var user = db.Users.Where(x => x.Id == this.User.UserId).FirstOrDefault();
}
@using System.Linq
@using Ehr.Common.Constraint
@using Ehr.Models
@using Ehr.ViewModels
@using Ehr.Common.UI;
@using System.ComponentModel.DataAnnotations;
@using Ehr.Auth;
@model List<ReportViewModel>
<style>
    .select2-container .select2-selection--single {
        height: calc(2.25rem + 2px);
        padding: .75rem 1rem;
        border: 1px solid #ced4da;
        display: block;
    }

    .select2-container {
        width: 100% !important;
    }

    .select2-selection__arrow {
        padding-top: 2rem;
    }
</style>
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5>
                        Thống kê tất cả khách hàng
                    </h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thống kê tất cả khách hàng</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="card">
            @using (Html.BeginForm("All", "Report", FormMethod.Get))
            {
                <div class="card-header">
                    <div class="card-tools float-right">
                        <div class="input-group input-group-sm float-right">
                            <div class="input-group-append" style="margin-top:5px">
                                Kích thước trang&nbsp;&nbsp;
                            </div>
                            @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();", @class = "form-control custom-select", @style = "border-radius:0px;width:55px;" })&nbsp;&nbsp;
                            @Html.Hidden("page", (object)ViewBag.page)
                            @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
                            @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
                            @Html.Hidden("size", (object)ViewBag.pageSize)
                            @Html.TextBox("SearchString", (string)ViewBag.searchValue, new { @class = "form-control", @type = "text", @placeholder = "Tìm...", @style = "border-radius:0px;width:200px" })
                            @Html.Hidden("page", (object)ViewBag.page)
                            @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
                            @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
                            @Html.Hidden("size", (object)ViewBag.pageSize)
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <!-- /.card-tools -->
            <div class="card-body table-responsive p-0 zoom-table">
                <div class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered table-hover dataTable">
                                <thead>
                                    <tr>
                                        <th style="width: 1%">
                                            STT
                                        </th>
                                        <th>Mã khách hàng</th>
                                        <th>Tên khách hàng</th>
                                        <th>Số điện thoại</th>
                                        <th>Địa chỉ</th>
                                        <th>Tổng đĩa đang thuê</th>
                                        <th>Tổng đĩa trễ hạn</th>
                                        <th>Tên đĩa</th>
                                        <th style="min-width:80px">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int dem = ViewBag.fromItem;
                                    }
                                    @foreach (var i in Model)
                                    {
                                        <tr>
                                            <td>
                                                @dem
                                                @{dem++;}
                                            </td>
                                            <td>
                                                @i.Code
                                            </td>
                                            <td>
                                                @i.Name
                                            </td>
                                            <td>
                                                @i.PhoneNumber
                                            </td>
                                            <td>
                                                @i.Address
                                            </td>
                                            <td>
                                                @i.DiskRentTotal
                                            </td>
                                            <td>
                                                @i.DiskLate
                                            </td>
                                            <td>
                                                @i.Disk
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    @Html.Raw(ViewBag.paging)
                </div>
            </div>
            <!-- /.card-body -->
        </div>

    </section>
    <!-- /.content -->
</div>

<div id="ezloader" style="display:none;position:absolute;top:50%;left:50%;padding:2px;">
    <img src="~/Content/img/loader.gif" />
</div>

@Scripts.Render("~/Content/admin-lte/plugins/datatables/jquery.dataTables.min.js")
@Scripts.Render("~/Content/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js")
@Styles.Render("~/Content/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css")
@{
    var loaderpath = Url.Action("Content/img/loader.gif", "/", null, Request.Url.Scheme);
}
<script>
    var flag = "/Disk/Disk"
</script>