QLTD/QLTD/ViewModels/RentViewModel.cs
using Ehr.Common.Constraint;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ehr.ViewModels
{
    public class RentViewModel
    {
        public int Id { get; set; }
        /// <summary>
        /// Mã phiếu thuê
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// ngày trả
        /// </summary>
        public int RentLenght { get; set; }
        /// <summary>
        /// Ngày thuê
        /// </summary>
        public string RentDate { get; set; }
        /// <summary>
        /// khách hàng
        /// </summary>
        public int CustomerId { get; set; }

        public string CustomerName { get; set; }
        /// <summary>
        /// khách hàng
        /// </summary>
        public RentStatus Status { get; set; }
    }
}

QLTD/QLTD/Controllers/RentDiskController.cs
using Ehr.Auth;
using Ehr.Bussiness;
using Ehr.Common.Constraint;
using Ehr.Common.UI;
using Ehr.Data;
using Ehr.Models;
using Ehr.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ehr.Controllers
{
    public class RentDiskController : BaseController
    {
        private readonly UnitWork unitWork;
        public RentDiskController(UnitWork unitWork)
        {
            this.unitWork = unitWork;
        }

        #region Rent
        // GET: RentDisk
        [PermissionBasedAuthorize("RENT_DISK")]
        public ActionResult Rent(string sortProperty, string sortOrder, string searchString, int? size, int? page)
        {
            var user = unitWork.User.GetById(this.User.UserId);
            if (String.IsNullOrEmpty(sortProperty)) sortProperty = "Code";
            //Mặc định là từ A-Z
            string nextSort = "";
            if (String.IsNullOrEmpty(sortOrder)) sortOrder = "desc";
            if (sortOrder.Equals("asc") | sortOrder.Equals("none")) nextSort = "desc";
            if (sortOrder.Equals("desc")) nextSort = "asc";


            //Tạo danh sách cho hiển thị số dòng trên lưới
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "35", Value = "35" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });
            items.Add(new SelectListItem { Text = "100", Value = "100" });
            items.Add(new SelectListItem { Text = "200", Value = "200" });
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }

            #region  xây dựng header cho lưới
            string header = "";
            //các cột cần hiển thị
            List<EZGridColumn> columns = new List<EZGridColumn>();
            //Lấy tất cả thuộc tính của city ra
            var properties = typeof(OrderRent).GetProperties();
            foreach (var item in properties)
            {
                if (item.Name.Equals("Code"))
                {
                    columns.Add(new EZGridColumn() { Name = item.Name, Text = "Mã phiếu thuê", Order = 2, AllowSorting = true });
                }
                if (item.Name.Equals("Customer"))
                {
                    columns.Add(new EZGridColumn() { Name = item.Name, Text = "Khách hàng", Order = 4, AllowSorting = true });
                }
                if (item.Name.Equals("RentDate"))
                {
                    columns.Add(new EZGridColumn() { Name = item.Name, Text = "Ngày thuê", Order = 3, AllowSorting = true });
                }
                if (item.Name.Equals("Status"))
                {
                    columns.Add(new EZGridColumn() { Name = item.Name, Text = "Trạng thái", Order = 4, AllowSorting = true });
                }
            }
            //sắp xếp lại các cột theo thứ tự
            columns = columns.OrderBy(c => c.Order).ToList();

            foreach (var col in columns)
            {
                if (col.AllowSorting)
                {
                    string basedUrl = "page=" + page + "&size=" + size + "&searchString=" + searchString + "&sortProperty=" + col.Name + "&sortOrder=";
                    if (sortOrder.Equals("desc") && sortProperty.Equals(col.Name))
                    {
                        header += "<th class='sorting_desc'><a style='display: block;' href='?" + basedUrl +
                            nextSort + "'>" + col.Text + "</th></a></th>";
                    }
                    else if (sortOrder.Equals("asc") && sortProperty.Equals(col.Name))
                    {
                        header += "<th class='sorting_asc'><a style='display: block;' href='?" + basedUrl +
                            nextSort + "'>" + col.Text + "</a></th>";
                    }
                    else
                    {
                        header += "<th class='sorting'><a  style='display: block;' href='?" + basedUrl +
                           nextSort + "'>" + col.Text + "</a></th>";
                    }
                }
                else header += "<th>" + col.Text + "</th>";
            }
            #endregion


            #region Phần sắp xếp
            Ehr.Data.QLTDDBContext db = new Data.QLTDDBContext();

            //Lấy dataset rỗng
            IQueryable<OrderRent> Rents = null;
            if (sortOrder.Equals("desc"))
            {
                if (sortProperty.Equals("Code"))
                    Rents = from c in db.Rents orderby c.Code descending select c;
                else if (sortProperty.Equals("Customer"))
                    Rents = from c in db.Rents orderby c.Customer.Name descending select c;
                else if (sortProperty.Equals("RentDate"))
                    Rents = from c in db.Rents orderby c.RentDate descending select c;
                else if (sortProperty.Equals("Status"))
                    Rents = from c in db.Rents orderby c.Status descending select c;
            }
            else
            {
                if (sortProperty.Equals("Code"))
                    Rents = from c in db.Rents orderby c.Code ascending select c;
                else if (sortProperty.Equals("Customer"))
                    Rents = from c in db.Rents orderby c.Customer.Name ascending select c;
                else if (sortProperty.Equals("RentDate"))
                    Rents = from c in db.Rents orderby c.RentDate ascending select c;
                else if (sortProperty.Equals("Status"))
                    Rents = from c in db.Rents orderby c.Status ascending select c;
            }
            #endregion

            #region Phần tìm kiếm
            if (!String.IsNullOrEmpty(searchString))
            {
                Rents = Rents.Where(c => c.Code.ToString().ToLower().Contains(searchString.ToLower())
                || c.RentDate.ToString().ToLower().Contains(searchString.ToLower())
                || c.Customer.Name.ToString().ToLower().Contains(searchString.ToLower())
                );

            }
            #endregion

            #region Phần phân trang		
            //Trang mặc định
            if (page == null) page = 1;
            //Số dòng mặc định
            int pageSize = (size ?? 10);
            // Đếm tổng số trang

            int datasetSize = 0;
            if (Rents != null)
                datasetSize = Rents.Count();
            int checkTotal = (int)(datasetSize / pageSize) + 1;
            // Nếu trang yêu cầu vượt qua tổng số trang thì thiết lập là tổng số trang
            if (page > checkTotal) page = checkTotal;
            string _url = "searchString=" + searchString + "&sortProperty=" + sortProperty + "&sortOrder=" + sortOrder;
            EZPaging ezpage = new EZPaging((page ?? 1), pageSize, datasetSize, _url);
            #endregion

            // Thiết lập các ViewBag
            ViewBag.GridHeader = header;// Header của lưới			
            ViewBag.searchValue = searchString;// Chuỗi tìm kiếm
            ViewBag.sortProperty = sortProperty;//Chọn cột sắp xếp
            ViewBag.sortOrder = nextSort;//Kiểu sắp xếp tiếp theo
            ViewBag.page = page;// Trang hiện tại
            ViewBag.size = items; //Danh sách cho chọn trang
            ViewBag.currentSize = size; //Số mục trên 1 trang được chọn
            ViewBag.pageSize = pageSize;//Số mục trên 1 trang để cache lại
            ViewBag.paging = ezpage.PageModel.HTML;//HTML cho đoạn phân trang
            ViewBag.fromItem = ezpage.PageModel.StartItem;
            ViewBag.DiskTitles = unitWork.DiskTitle.Get().ToList();
            var enumstatus = Enum.GetValues(typeof(RentStatus))
                          .Cast<RentStatus>()
                          .ToList();
            ViewBag.ListStatus = from s in enumstatus
                                 select new SelectListItem
                                 {
                                     Value = ((int)s).ToString(),
                                     Text = s.GetAttribute<DisplayAttribute>().Name
                                 };
            ViewBag.Customer = unitWork.Customer.Get(x => x.Status != CustomerStatus.INACTIVE);
            ViewBag.DiskTitles = unitWork.DiskTitle.Get(x => x.Status == TitleStatus.PENDING);
            //Hiển thị trong khoảng chọn
            if (Rents != null)
                if (ezpage.PageModel.StartItem >= 1 && datasetSize > 0)
                {
                    return View(Rents.Skip(ezpage.PageModel.StartItem - 1).Take(ezpage.PageModel.StopItem - ezpage.PageModel.StartItem + 1).ToList());
                }
                else
                {
                    return View(Rents.ToList());
                }

            else
                return View((from c in db.Rents select c).ToList());
        }

        [PermissionBasedAuthorize("RENT_DISK")]
        public JsonResult GetRent(int? Id)
        {
            try
            {
                if(Id != null)
                {
                    var Rent = unitWork.Rent.GetById(Id);
                    var rentview = new RentViewModel();
                    rentview.Id = Rent.Id;
                    rentview.Code = Rent.Code;
                    rentview.RentLenght = Rent.RentLenght;
                    rentview.RentDate = DataConverter.DateTime2UI_Full(Rent.RentDate);
                    rentview.CustomerId = Rent.Customer.Id;
                    rentview.CustomerName = Rent.Customer.Name;

                    var lsrentviewdetail = new List<RentDetailViewModel>();
                    foreach (var item in Rent.RentDetails)
                    {
                        var rentviewdetail = new RentDetailViewModel();

QLTD/QLTD/Views/RentDisk/Receipt.cshtml
@{
    ViewBag.Title = "Danh sách đĩa chưa trả";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Ehr.Data.QLTDDBContext db = new Ehr.Data.QLTDDBContext();
    var user = db.Users.Where(x => x.Id == this.User.UserId).FirstOrDefault();
    var datenow = DataConverter.DateTime2UI_Full(DateTime.Now);
}
@using System.Linq
@using Ehr.Common.Constraint
@using Ehr.Models
@using Ehr.Common.UI;
@using System.ComponentModel.DataAnnotations;
@using Ehr.Auth;
@model IEnumerable<Ehr.Models.OrderRent>
<style>
    .select2-container .select2-selection--single {
        height: calc(2.25rem + 2px);
        padding: .75rem 1rem;
        border: 1px solid #ced4da;
        display: block;
    }

    .select2-container {
        width: 100% !important;
    }

    .select2-selection__arrow {
        padding-top: 2rem;
    }
</style>
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5>
                        Danh sách đĩa chưa trả
                    </h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Danh sách đĩa chưa trả</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="card">
            @using (Html.BeginForm("Receipt", "RentDisk", FormMethod.Get))
            {
                <div class="card-header">
                    <div class="card-tools float-right">
                        <div class="input-group input-group-sm float-right">
                            <div class="input-group-append" style="margin-top:5px">
                                Kích thước trang&nbsp;&nbsp;
                            </div>
                            @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();", @class = "form-control custom-select", @style = "border-radius:0px;width:55px;" })&nbsp;&nbsp;
                            @Html.Hidden("page", (object)ViewBag.page)
                            @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
                            @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
                            @Html.Hidden("size", (object)ViewBag.pageSize)
                            @Html.TextBox("SearchString", (string)ViewBag.searchValue, new { @class = "form-control", @type = "text", @placeholder = "Tìm...", @style = "border-radius:0px;width:200px" })
                            @Html.Hidden("page", (object)ViewBag.page)
                            @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
                            @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
                            @Html.Hidden("size", (object)ViewBag.pageSize)
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <!-- /.card-tools -->
            <div class="card-body table-responsive p-0 zoom-table">
                <div class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered table-hover dataTable">
                                <thead>
                                    <tr>
                                        <th style="width: 1%">
                                            STT
                                        </th>
                                        @Html.Raw(ViewBag.GridHeader)
                                        <th style="width: 15%">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int dem = ViewBag.fromItem;
                                    }
                                    @foreach (var i in Model)
                                    {
                                    <tr>
                                        <td>
                                            @dem
                                            @{dem++;}
                                        </td>
                                        @{
                                            var datea = DataConverter.DateTime2UI_Full(i.RentDate);
                                            var dateare = DataConverter.DateTime2UI_Full(i.ReceiptDate);
                                            var state = i.Status.GetAttribute<DisplayAttribute>().Name;
                                            var bg = "";
                                            if (i.Status == RentStatus.RENTING)
                                            {
                                                bg = "bg-warning";
                                            }
                                            if (i.Status == RentStatus.PENDING)
                                            {
                                                bg = "bg-primary";
                                            }
                                            else if (i.Status == RentStatus.DONE)
                                            {
                                                bg = "bg-success";
                                            }
                                        }
                                        <td>
                                            @i.Code
                                        </td>
                                        <td>
                                            @datea
                                        </td>
                                        <td>
                                            @dateare
                                        </td>
                                        <td>
                                            @i.Customer.Name
                                        </td>
                                        <td>
                                            <span class="badge @bg">@state</span>
                                        </td>
                                        <td class="project-actions text-right">
                                            @if (i.Status != RentStatus.DONE)
                                            {
                                                <a href="../../RentDisk/ReceiptDisk?id=@i.Id" class="btn btn-success btn-sm">
                                                    <span>Trả đĩa</span>
                                                    <i class="fas fa-arrow-circle-right">
                                                    </i>
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    @Html.Raw(ViewBag.paging)
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- Default box -->
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>

<div id="ezloader" style="display:none;position:absolute;top:50%;left:50%;padding:2px;">
    <img src="~/Content/img/loader.gif" />
</div>

@Scripts.Render("~/Content/admin-lte/plugins/datatables/jquery.dataTables.min.js")
@Scripts.Render("~/Content/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js")
@Styles.Render("~/Content/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css")
@{
    var loaderpath = Url.Action("Content/img/loader.gif", "/", null, Request.Url.Scheme);
}
<script>
    var flag = "/RentDisk/Receipt"
</script>
<script>
    $(document).ajaxStart(function () {
        $("#ezloader").css("display", "block");
    });

    $(document).ajaxComplete(function () {
        $("#ezloader").css("display", "none");
    });
</script>